### ISSUE TITLE
Deployment segítése

### ISSUE THREAD

**Issue by bmaidics** [BME-MIT-IET/Nekem-is-iet-2018#1]
Deployment segítésére hasznos lenne valamilyen eszköz használata. Pl.: Docker

**Comment by matefelegyhazy** [comment]
Megcsináltam 😄 Létrehoztam egy úgy branchet [docker-init](https://github.com/BME-MIT-IET/Nekem-is-iet-2018/tree/docker-init) néven. Készültek PowerShell scriptek is, hogy csak pár kattintás legyen az egész konfigurálása.
Csináltam egy pull request-et, @vadlevente kollégára vár az elbírálása 😇
