### ISSUE TITLE
CI beüzemelése

### ISSUE THREAD

**Issue by matefelegyhazy** [BME-MIT-IET/Nekem-is-iet-2018#2]
A jövőbeni automatizált unit tesztekhez jól jönne. Használhatnánk pl.: Travis-t, ami a gyakorlaton volt, de [ezt is megnézhetnéd.](https://developer.android.com/studio/projects/continuous-integration)

**Comment by bmaidics** [comment]
Sikerült beüzemelni a CI-t. Végül travist választottam. 
A projekt struktúrát át kellett rendeznem, mert a build.gradle-t a home könyvtárban keresi.
A gradlew alapvetően nem futtatható, viszont travis ezt mindenképpen szerette volna futtatni. A "chmod +x ./gradlew" parancs kiadásával ezt megoldottam.

Commit link: https://github.com/BME-MIT-IET/Nekem-is-iet-2018/commit/82fbe03119ef5e54b118be6afec06471b07363b9

**Comment by matefelegyhazy** [comment]
Szuper, megnéztem :) Látom azért meggyűlt vele a bajod, kellett pár próbálkozás :D
