### ISSUE TITLE
Statikus kódanalízis

### ISSUE THREAD

**Issue by littletof** [BME-MIT-IET/Nekem-is-iet-2018#3]

**Comment by littletof** [comment]
Sikeresen beüzemeltem, a Findbugs programot analizálót használtam hozzá.

Futtatáshoz a terminálban a ```gradlew findbugs``` parancsot kell kiadni, ami ezután az analízis eredményét az ```app/build/outputs/findbugs/findbugs.html``` fájlban jeleníti meg


Commit [link](https://github.com/BME-MIT-IET/Nekem-is-iet-2018/commit/5b3dea2eeaa57d7fcdebb8d22d8bd6d0b8f74e99)

**Comment by littletof** [comment]
A statikus ellenőrzéshez és az adott hibák javításához új ágat hoztam létre: [```staticanalisys```](https://github.com/BME-MIT-IET/Nekem-is-iet-2018/tree/staticanalisys)

Az analízis **Bad practice Warnings** közül filterrel letiltottam a ```NM_CLASS_NAMING_CONVENTION``` típusú riasztásokat ```R``` és a ```Manifest``` fájlokra, mivel ezekre az osztályokra nincs ráhatásunk, a hibajelzések így itt nem hasznosak.

Commits: [R](https://github.com/BME-MIT-IET/Nekem-is-iet-2018/commit/3d067a4c986edc08df8a12664383086706381c4a), [Manifest](https://github.com/BME-MIT-IET/Nekem-is-iet-2018/commit/5c94ea750160edd35d674d87428cb9fa11d75300)

**Comment by vadlevente** [comment]
A Bad practice Warnings között találtam egy DMI_RANDOM_USED_ONLY_ONCE típusú hibát, ennek kijavítására a véletlen szám hatékony generálásához felvettem egy random mezőt, hogy generáláskor azon hívjuk a nextInt() metódust, ne egy új Random objektumon

Commit: [https://github.com/BME-MIT-IET/Nekem-is-iet-2018/commit/11c16cc530289c32a9d0879451df6b85ee5341e9](url)

**Comment by vadlevente** [comment]
A Performance Warnings közül megszüntettem az egyik URF_UNREAD_FIELD típusú hibát, amely olyan mezőket jelöl meg, amelyeket inicializálásuk után nem használunk. Ehhez töröltem a megfelelő mezőt

Commit:[https://github.com/BME-MIT-IET/Nekem-is-iet-2018/commit/90ec96d82aeb8d4c8911b4ae4a28559877eb671f](url)

**Comment by vadlevente** [comment]
A Performance Warnings közül megszüntettem egy SIC_INNER_SHOULD_BE_STATIC típusú hibát. Egy osztályon belül létrehozott osztály nem használja a külső osztály referenciáját, ezért lehet statikus is

Commit: [https://github.com/BME-MIT-IET/Nekem-is-iet-2018/commit/fc54c811bfc0f62145c91cee58244e34b3482798](url)

**Comment by vadlevente** [comment]
A Dodgy code Warning közül megszüntettem egy SF_SWITCH_NO_DEFAULT típusú hibát. Ezt olyan switch-case szerkezetekre kaphatjuk, ahol nem adtunk meg default opciót. Ehhez az adott switchben felvettem egy default ágat is

Commit:[https://github.com/BME-MIT-IET/Nekem-is-iet-2018/commit/a98c69c8d1eb81d34ad5b126fb10a7881d58b6ec](url)

**Comment by littletof** [comment]
Az R.java fájlba mutató MS_MUTABLE_ARRAY warningok szűrése, mivel az R fájl automatikusan generált, így nincs ráhatásunk.

Commit: [link](https://github.com/BME-MIT-IET/Nekem-is-iet-2018/commit/3da009a78ce6e35199b4d1d5e6da2fffef4d3d51)

**Comment by matefelegyhazy** [comment]
Kipróbáltam, elsőre nem futott le, hibát dobott a findbugs parancs. Másodjára sikeresen lefutott, viszont nem generálta le a fent említett file-t. 👿  Szerencsére három a magyar igazsság, és végül működött. 😀 
Tök jó, hogy linkeltétek a commitokat 👍 Mondjuk @vadlevente linkjei 404-et dobnak, mert habár a link szövegei jók, viszont mindegyik erre mutat:  [https://github.com/BME-MIT-IET/Nekem-is-iet-2018/issues/url](https://github.com/BME-MIT-IET/Nekem-is-iet-2018/issues/url) 😆
