### ISSUE TITLE
UI tesztelés

### ISSUE THREAD

**Issue by bmaidics** [BME-MIT-IET/Nekem-is-iet-2018#6]
A felhasználói élmény javítása érdekében hasznos lenne UI tesztet készíteni.

**Comment by matefelegyhazy** [comment]
megkezdtük @vadlevente kollégával 😎 a [ui-test](https://github.com/BME-MIT-IET/Nekem-is-iet-2018/tree/ui-test) ágon folyik a munka 💻

**Comment by matefelegyhazy** [comment]
készültek tesztek a bejelentkezéshez/kijelentkezéshez/kategóriák módosításához, kezdeményeztem a [ui-test](https://github.com/BME-MIT-IET/Nekem-is-iet-2018/tree/ui-test) ág mergeölését a [master](https://github.com/BME-MIT-IET/Nekem-is-iet-2018/tree/master) ágra: [pull request](https://github.com/BME-MIT-IET/Nekem-is-iet-2018/pull/8)

**Comment by littletof** [comment]
a teszteket megnéztem, megfelelően működnek, mergelem az ágat, az issuet lezárom.
