### ISSUE TITLE
Unit teszt

### ISSUE THREAD

**Issue by vadlevente** [BME-MIT-IET/Nekem-is-iet-2018#7]
Unit tesztekre is szükség lenne.

**Comment by bmaidics** [comment]
Csináltam unit tesztet a kategóriák egyenlőségének, nem egyenlőségének vizsgálatára, valamit a reportok esetén a kiadások összegzését is teszteltem. Kétféle módon: egyik az összes kiadást összeadja, a másik csak a megadott két dátum között lévőt. 
Az összes általam tesztelt funkció tökéletesen működött.
